default:
  before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  
variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - deploy

build-container:
  stage: build
  script:
    - echo "Building container..."
    - docker build . -t $IMAGE_NAME
    - echo "Finished building container."

test-compose-stack:
  stage: test
  script:
    - docker compose up -d
    - sleep 60
    - docker compose down

push-to-registry:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - docker image push $IMAGE_NAME
    - echo "Application successfully deployed."
